version: '3'
services:
    pmaverick-webserver:
        container_name: webserver
        image: nginx:alpine
        ports: 
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/html